# Generated by Django 5.1.2 on 2024-11-04 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PageVist',
            new_name='PageVisit',
        ),
    ]
